DECLARE
TYPE REG1 IS RECORD(
V1 number,
V2 varchar2(40));

VAR1 REG1;
VAR1.V2='HOLA';
VAR1.V1=14;

/** SE PODRÁ ASIGNAR UN SELECT QUE DEVUELVA 2 COLUMNAS CON LOS TIPOS DE REG1
SELECT C1,C2 INTO VAR1*/